import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./services/MenuContext";
import { CategoryProvider } from "./category/components/context/CategoryContext";
import { FoodProvider } from "./food/components/context/FoodContext";
import { MenuProvider } from "./menu/components/context/menuContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuProvider>
          <CategoryProvider>
            <FoodProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </FoodProvider>
          </CategoryProvider>
        </MenuProvider>
      </body>
    </html>
  );
}
